name: Test Action
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run build
      - run: git status --porcelain
      - run: echo "${{ secrets.GHA_SECRETS_TEST }}" | md5sum
      - name: Keep previous test value
        id: previous
        run: echo '::set-output name=value::${{ secrets.GHA_SECRETS_TEST }}'
      - name: Gen new random secret
        id: new
        run: |
          new_value=$(cat /dev/random | tr -dc 'a-zA-Z0-9' | head -c10)
          echo "::set-output name=value::$new_value"
      - uses: ./.
        with:
          token: ${{ secrets.TOKEN }}
          name: 'GHA_SECRETS_TEST'
          value: ${{ steps.new.outputs.value }}
