name: Test Action
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 17 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
          npm run build
      - run: git status --porcelain
      - run: echo "${{ secrets.GHA_SECRETS_TEST }}" | md5sum
      - name: Keep previous test value
        id: previous
        run: echo "value=${{ secrets.GHA_SECRETS_TEST }}" >> $GITHUB_OUTPUT
      - name: Gen new random secret
        id: new
        run: echo "value=$(tr -dc 'a-zA-Z0-9' < /dev/random | head -c10)" >> $GITHUB_OUTPUT
      - uses: ./.
        with:
          token: ${{ secrets.TOKEN }}
          name: 'GHA_SECRETS_TEST'
          value: ${{ steps.new.outputs.value }}
